### ISSUE TITLE
Unable to install windows .msi

### ISSUE THREAD

**Issue by ramya0528** [chef-cookbooks/omnibus_updater#110]
# When I run this cookbook, by overriding the attribute 'directurl', I am receiving following error:

 Recipe Compile Error in c:/chef/cache/cookbooks/wrapper_omnibus_updater/recipes/default.rb
 ================================================================================

 Chef::Exceptions::ResourceNotFound

---

 Cannot find a resource matching execute[omnibus_install[chef-client-12.9.41-x64.msi]](did you define it first?)

 Cookbook Trace:

---

   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_set.rb:63:in `lookup'
   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_set.rb:142:in`block (2 levels) in fi
urce_by_hash'
   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_set.rb:141:in `each'
   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_set.rb:141:in`block in find_resource
h'
   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_set.rb:139:in `each'
   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_set.rb:139:in`find_resource_by_hash'
   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_set.rb:85:in `block in find'
   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_set.rb:82:in`each'
   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_set.rb:82:in `find'
   C:/opscode/chef/embedded/apps/chef/lib/chef/recipe.rb:90:in`resources'
   c:/chef/cache/cookbooks/wrapper_omnibus_updater/recipes/default.rb:14:in `from_file'
   C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in`instance_eval'
   C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
   C:/opscode/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in`load_recipe'
   C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
   C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in`block in compile_recipes'
   C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
   C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in`compile_recipes'
   C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
   C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in`load'
   C:/opscode/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
   C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:256:in`setup_run_context'
   C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:454:in `run'
   C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in`run_with_graceful_exit_option'
   C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
   C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in`with_server_connectivity'
   C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
   C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in`block in interval_run_chef_client'
   C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
   C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in`interval_run_chef_client'
   C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
   C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in`run'
   C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
   C:/opscode/chef/bin/chef-client:63:in`load'
   C:/opscode/chef/bin/chef-client:63:in `<main>'

**Comment by tas50** [comment]
We're not seeing this issue with the latest release. Try updating to 3.0
