### ISSUE TITLE
Omnibus updater not installing latest client 12.11.18

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/omnibus_updater#112]
getting action nothing on linux install of lastest client, and windows is not getting the right file and thus fails to try and install lastest client 12.11.18. Currently running on CentOS 6.7 with chef-client 12.10.24 and WIndows 2012 R2 with chef-client 12.10.24.

**Comment by Stromweld** [comment]
Here's a snippet from linux run:

Recipe: omnibus_updater::downloader
  * directory[/var/chef/cache/omnibus_updater] action create (up to date)
  * remote_file[omnibus_remote[chef-12.11.18-1.el6.x86_64.rpm]] action create_if_missing (skipped due to only_if)
Recipe: omnibus_updater::installer
  * service[chef-client] action nothing (skipped due to action :nothing)
  * file[/tmp/nocheck] action create (skipped due to only_if)
  * ruby_block[omnibus chef killer] action nothing (skipped due to action :nothing)
  * execute[omnibus_install[chef-12.11.18-1.el6.x86_64.rpm]] action nothing (skipped due to action :nothing)
  * ruby_block[Omnibus Chef install notifier] action nothing (skipped due to action :nothing)

**Comment by Stromweld** [comment]
Here's snippet from windows run:

Recipe: omnibus_updater::downloader
  * directory[c:/chef/cache/omnibus_updater] action create[2016-06-15T16:55:05-05:00] INFO: Processing directory[c:/chef
/cache/omnibus_updater] action create (omnibus_updater::downloader line 38)
[2016-06-15T16:55:05-05:00] INFO: directory[c:/chef/cache/omnibus_updater] created directory c:/chef/cache/omnibus_updat
er

    - create new directory c:/chef/cache/omnibus_updater
  * remote_file[omnibus_remote[chef-client-12.11.18-1-x64.msi]] action create_if_missing[2016-06-15T16:55:05-05:00] INFO
: Processing remote_file[omnibus_remote[chef-client-12.11.18-1-x64.msi]] action create_if_missing (omnibus_updater::down
loader line 42)
 (skipped due to only_if)
Recipe: omnibus_updater::installer
  * windows_service[chef-client] action nothing[2016-06-15T16:55:05-05:00] INFO: Processing windows_service[chef-client]
 action nothing (omnibus_updater::installer line 23)
 (skipped due to action :nothing)
  * execute[chef-uninstall] action nothing[2016-06-15T16:55:05-05:00] INFO: Processing execute[chef-uninstall] action no
thing (omnibus_updater::installer line 34)
 (skipped due to action :nothing)
  * execute[chef-install] action nothing[2016-06-15T16:55:05-05:00] INFO: Processing execute[chef-install] action nothin
g (omnibus_updater::installer line 38)
 (skipped due to action :nothing)
  * execute[chef-service-kill] action nothing[2016-06-15T16:55:05-05:00] INFO: Processing execute[chef-service-kill] act
ion nothing (omnibus_updater::installer line 43)
 (skipped due to action :nothing)
  * ruby_block[Omnibus Chef Update] action run[2016-06-15T16:55:05-05:00] INFO: Processing ruby_block[Omnibus Chef Updat
e] action run (omnibus_updater::installer line 48)
[2016-06-15T16:55:05-05:00] INFO: ruby_block[Omnibus Chef Update] called

    - execute the ruby block Omnibus Chef Update
[2016-06-15T16:55:05-05:00] INFO: ruby_block[Omnibus Chef Update] sending run action to execute[chef-service-kill] (imme
diate)
  * execute[chef-service-kill] action run[2016-06-15T16:55:05-05:00] INFO: Processing execute[chef-service-kill] action
run (omnibus_updater::installer line 43)

    [execute]
              INFO: No tasks running with the specified criteria.
[2016-06-15T16:55:05-05:00] INFO: execute[chef-service-kill] ran successfully
    - execute taskkill /F /FI "SERVICES eq chef-client"
[2016-06-15T16:55:05-05:00] INFO: ruby_block[Omnibus Chef Update] sending run action to execute[chef-uninstall] (immedia
te)
  * execute[chef-uninstall] action run[2016-06-15T16:55:05-05:00] INFO: Processing execute[chef-uninstall] action run (o
mnibus_updater::installer line 34)

    [execute] Executing (\\IP-AC15100C\ROOT\CIMV2:Win32_Product.IdentifyingNumber="{689C12FC-59BC-4B51-B368-B16F050147CB
}",Name="Chef Client v12.11.18",Version="12.11.18.1")->Uninstall()
              Method execution successful.
              Out Parameters:
              instance of __PARAMETERS
              {
                ReturnValue = 0;
              };

[2016-06-15T16:55:10-05:00] INFO: execute[chef-uninstall] ran successfully
    - execute wmic product where "name like 'Chef Client%% %%'" call uninstall /nointeractive
[2016-06-15T16:55:10-05:00] INFO: ruby_block[Omnibus Chef Update] sending run action to execute[chef-install] (immediate
)
  * execute[chef-install] action run[2016-06-15T16:55:10-05:00] INFO: Processing execute[chef-install] action run (omnib
us_updater::installer line 38)

    [execute] T h i s   i n s t a l l a t i o n   p a c k a g e   c o u l d   n o t   b e   o p e n e d .     V e r i f
y   t h a t   t h e   p a c k a g e   e x i s t s   a n d   t h a t   y o u   c a n   a c c e s s   i t ,   o r   c o n
t a c t   t h e   a p p l i c a t i o n   v e n d o r   t o   v e r i f y   t h a t   t h i s   i s   a   v a l i d   W
i n d o w s   I n s t a l l e r   p a c k a g e .

    ←[0m
    ================================================================================
    Error executing action `run` on resource 'execute[chef-install]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1619'
    ---- Begin output of msiexec.exe /qn /i chef-client-12.11.18-1-x64.msi ADDLOCAL="ChefClientFeature,ChefPSModuleFeatu
re,ChefServiceFeature" ----
    STDOUT: T h i s   i n s t a l l a t i o n   p a c k a g e   c o u l d   n o t   b e   o p e n e d .     V e r i f y
  t h a t   t h e   p a c k a g e   e x i s t s   a n d   t h a t   y o u   c a n   a c c e s s   i t ,   o r   c o n t
a c t   t h e   a p p l i c a t i o n   v e n d o r   t o   v e r i f y   t h a t   t h i s   i s   a   v a l i d   W i
n d o w s   I n s t a l l e r   p a c k a g e .
    STDERR:
    ---- End output of msiexec.exe /qn /i chef-client-12.11.18-1-x64.msi ADDLOCAL="ChefClientFeature,ChefPSModuleFeature
,ChefServiceFeature" ----
    Ran msiexec.exe /qn /i chef-client-12.11.18-1-x64.msi ADDLOCAL="ChefClientFeature,ChefPSModuleFeature,ChefServiceFea
ture" returned 1619

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:49:in `block in run_actio
n'
    c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `each'
    c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `run_action'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/omnibus_updater/recipes/installer.rb

     38:     execute 'chef-install' do
     39:       command "msiexec.exe /qn /i #{File.basename(remote_path)} ADDLOCAL=\"#{node[:omnibus_updater][:addlocal]}
\""
     40:       cwd node[:omnibus_updater][:cache_dir]
     41:       action :nothing
     42:     end
     43:     execute 'chef-service-kill' do

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/omnibus_updater/recipes/installer.rb:38:in `from_file'

    execute("chef-install") do
      action [:nothing]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "msiexec.exe /qn /i chef-client-12.11.18-1-x64.msi ADDLOCAL=\"ChefClientFeature,ChefPSModuleFeature,ChefSe
rviceFeature\""
      backup 5
      cwd "c:/chef/cache/omnibus_updater"
      returns 0
      declared_type :execute
      cookbook_name "omnibus_updater"
      recipe_name "installer"
    end

    Platform:
    ---------
    x64-mingw32

[2016-06-15T16:55:11-05:00] INFO: Running queued delayed notifications before re-raising exception
[2016-06-15T16:55:11-05:00] INFO: ad_nativex_rename[TAW2AM-IISTST01] sending request_reboot action to reboot[adjoin] (de
layed)
Recipe: ad-nativex::joindomain
  * reboot[adjoin] action request_reboot[2016-06-15T16:55:11-05:00] INFO: Processing reboot[adjoin] action request_reboo
t (ad-nativex::joindomain line 79)
[2016-06-15T16:55:11-05:00] WARN: Reboot requested:'adjoin'
[2016-06-15T16:55:11-05:00] INFO: Changing reboot status from {} to {:delay_mins=>1, :reason=>"Opscode Chef initiated re
boot. Restarting computer in 60 seconds!", :timestamp=>2016-06-15 16:55:11 -0500, :requested_by=>"adjoin"}

    - request a system reboot to occur if the run succeeds
←[0m
Running handlers:
[2016-06-15T16:55:11-05:00] ERROR: Running exception handlers
Running handlers complete
[2016-06-15T16:55:11-05:00] ERROR: Exception handlers complete
Chef Client failed. 26 resources updated in 01 minutes 55 seconds
[2016-06-15T16:55:11-05:00] INFO: Sending resource update report (run-id: e2439006-00c0-4fa8-a47a-388c8366c253)
[2016-06-15T16:55:11-05:00] ERROR: SSL Validation failure connecting to host: chef-server.teamfreeze.com - SSL_connect r
eturned=1 errno=0 state=error: certificate verify failed
[2016-06-15T16:55:11-05:00] ERROR: Failed to post reporting data to server (SSL Error connecting to https://chef-server.
teamfreeze.com/organizations/nativex/reports/nodes/TAW2AM-IISTST01/runs/e2439006-00c0-4fa8-a47a-388c8366c253 - SSL_conne
ct returned=1 errno=0 state=error: certificate verify failed)
[2016-06-15T16:55:11-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2016-06-15T16:55:11-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-06-15T16:55:11-05:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[chef-install] (omnibus_updater::install
er line 38) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1619'
---- Begin output of msiexec.exe /qn /i chef-client-12.11.18-1-x64.msi ADDLOCAL="ChefClientFeature,ChefPSModuleFeature,C
hefServiceFeature" ----
STDOUT: T h i s   i n s t a l l a t i o n   p a c k a g e   c o u l d   n o t   b e   o p e n e d .     V e r i f y   t
h a t   t h e   p a c k a g e   e x i s t s   a n d   t h a t   y o u   c a n   a c c e s s   i t ,   o r   c o n t a c
t   t h e   a p p l i c a t i o n   v e n d o r   t o   v e r i f y   t h a t   t h i s   i s   a   v a l i d   W i n d
o w s   I n s t a l l e r   p a c k a g e .
STDERR:
---- End output of msiexec.exe /qn /i chef-client-12.11.18-1-x64.msi ADDLOCAL="ChefClientFeature,ChefPSModuleFeature,Che
fServiceFeature" ----
Ran msiexec.exe /qn /i chef-client-12.11.18-1-x64.msi ADDLOCAL="ChefClientFeature,ChefPSModuleFeature,ChefServiceFeature
" returned 1619
The system cannot find the path specified.
PS C:\Users\Administrator> chef-client -r 'role[iis-mobile-default]' --node-name TAW2AM-IISTST01 --environment iis-mobil
e-default-dev
chef-client : The term 'chef-client' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ chef-client -r 'role[iis-mobile-default]' --node-name TAW2AM-IISTST01 --environm ...
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (chef-client:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Stromweld** [comment]
I also noticed this cookbook is still using the url prefix http://www.chef.io/chef/download to download packages and should probably be updated to something more like https://packages.chef.io/stable/windows/2008r2/chef-client-12.11.18-1-x64.msi with obviously correct OS and version for platform currently running on.

**Comment by tas50** [comment]
We had some issues with chef-client upgrades on Windows. We did a bit of refactoring and this *should* be working at this point. Can you give the latest cookbook a try and open this issue back up if you're still having problems.

**Comment by Stromweld** [comment]
since the refactor to move the opscode folder and delete on subsequent run, we have not had any problems with the last few chef-client updates on windows.

**Comment by tas50** [comment]
👍
