### ISSUE TITLE
fails on sucessful service restart

### ISSUE THREAD

**Issue by kevsgithub** [chef-cookbooks/omnibus_updater#113]
ubuntu vivid (16.10) systemd
omnibus_updater-1.1.0
updater successfully updates to latest client (12.11.18) and restarts service but reports it didn't.

`#<Mixlib::ShellOut::ShellCommandFailed: service[chef-client] (omnibus_updater::installer line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '' ---- Begin output of /bin/systemctl restart chef-client ---- STDOUT: STDERR: ---- End output of /bin/systemctl restart chef-client ---- Ran /bin/systemctl restart chef-client returned > had an error:
service[chef-client] (omnibus_updater::installer line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '' ---- Begin output of /bin/systemctl restart chef-client ---- STDOUT: STDERR: ---- End output of /bin/systemctl restart chef-client ---- Ran /bin/systemctl restart chef-client returned`

`Expected process to exit with [0], but received ''
---- Begin output of /bin/systemctl restart chef-client ----
STDOUT: 
STDERR: 
---- End output of /bin/systemctl restart chef-client ----
Ran /bin/systemctl restart chef-client returned`

If I run it manually
`sudo /bin/systemctl restart chef-client && echo $?`
reports 0.

There is no output on STDOUT or STDERR. I believe everything is working fine. The next time the client runs it reports the new version.

**Comment by tas50** [comment]
At this time we've chosen to deprecate the omnibus_updater cookbook in favor of our new chef_client_updater cookbook. I'm going to close this issue out as we will not be updating or releasing new versions of this codebase. Check out the new code at https://github.com/chef-cookbooks/chef_client_updater
