### ISSUE TITLE
Omnibus_updater chef-client upgrade leaves previosuly downloaded gems unusable

### ISSUE THREAD

**Issue by r2oro** [chef-cookbooks/omnibus_updater#122]
I have ran into an issue upgrading chef-client using omnibus_updater cookbook.
It upgrades Chef omnibus rpm on my rhel Linux hosts, leaving gem files downloaded by previous Chef runs in place.
However despite that they are listed by 'gem list' they are not usable. For example 'bluepill' (used to run chef-client itself) fails with following error:

```
---- Begin output of /opt/chef/embedded/bin/bluepill load /etc/bluepill/chef-client.pill ----
STDOUT:
STDERR: /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'activesupport' (< 5, >= 3.2) among 91 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/geadmin/.gem/ruby/2.1.0:/opt/chef/embedded/lib/ruby/gems/2.1.0', execute `gem env` for more information
    from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1428:in `each'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1428:in `activate_dependencies'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1410:in `activate'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
    from /opt/chef/embedded/bin/bluepill:22:in `<main>'
---- End output of /opt/chef/embedded/bin/bluepill load /etc/bluepill/chef-client.pill ----
```

In this case the issue is caused by lack of activesupport gem which was part of chef 12.5.1 and is not present in 12.11.18... I suppose that omnibus_updater apart of running "rpm -U" should cleanup gem directory, allowing necessary gems to be pulled once again together with all their dependencies which might have been removed in scope of upgrade

**Comment by brentm5** [comment]
I think this might be an issue with the chef-client RPM.  We had a similar issue when upgrading from 12.9.41 to 12.11.18 via the shell install script.  Although the missing library was different.  a complete uninstall and reinstall fixed the issue but I am not sure why the issue was caused.

**Comment by tas50** [comment]
At this time we've chosen to deprecate the omnibus_updater cookbook in favor of our new chef_client_updater cookbook. I'm going to close this issue out as we will not be updating or releasing new versions of this codebase. Check out the new code at https://github.com/chef-cookbooks/chef_client_updater
