### ISSUE TITLE
no implicit conversion of nil into String in 1.2.0

### ISSUE THREAD

**Issue by kpmueller** [chef-cookbooks/omnibus_updater#123]
Seeing this now in our setup - see attachment for trace. This is in EC2 Ubuntu 14.04, fresh node.
[chef.txt](https://github.com/chef-cookbooks/omnibus_updater/files/425930/chef.txt)

**Comment by tas50** [comment]
I'll get to the bottom of this. Thanks for the report @kpmueller

**Comment by chalettu** [comment]
We also see this happening in 1.2.0.

**Comment by spion06** [comment]
I submitted https://github.com/chef-cookbooks/omnibus_updater/pull/124 for this. looks like there were some string -> symbol issues

**Comment by kpmueller** [comment]
Thank you, that fixed it for me!
