### ISSUE TITLE
Version 'Did not find path' Issue on older MacOS systems

### ISSUE THREAD

**Issue by Elias-from-Testfabrik** [chef-cookbooks/omnibus_updater#126]
There seems to be an issue on MacOS X 10.9 with constructing the download link:
![stacktrace](https://cloud.githubusercontent.com/assets/18596992/17928158/b0ea13ba-69f9-11e6-9503-01f03165b758.png)

We use the following configuration.
- ['omnibus_updater']['restart_chef_service'] = true
- ['omnibus_updater']['version'] = '12.5.1'
- ['omnibus_updater']['prevent_downgrade'] = false
- ['omnibus_updater']['force_latest'] = false
- ['omnibus_updater']['preview'] = false
- ['omnibus_updater']['kill_chef_on_upgrade'] = true

The very same code and config works on the newer OS aka 10.10 and 10.11, I have not tried older ones (10.8 and lower) yet. Note that there are valid official download links for the chef-client down to 10.8 (https://packages.chef.io/stable/mac_os_x/10.8/chef-12.5.1-1.dmg).

EDIT: issue has been fixed in a fork we created, pull-request pending at time of writing

**Comment by Elias-from-Testfabrik** [comment]
The issue is probably related to the way the OmnibusTrucker builds the URL but I agree that the code looks fine on first glance there...

**Comment by Elias-from-Testfabrik** [comment]
Alright, the issue is this line in omnitrucker.rb:
`@attrs = { platform: set['platform_family'], platform_version: [[major, minor].join('.'), '10.7'].min }`

10.8 is correctly constructed as a string, compared with 10.7 and the min then ensures that the incorrect OS is selected. The URL constructed is synactically valid then but does not lead to a valid download since for chef-client 12.5.1, no such download exists (supports only down to 10.8).

Aka, the _min_ here is the incorrect function!

**Comment by Elias-from-Testfabrik** [comment]
I have created a pull-request. If accepted, you can close this issue.

Until then, we are using our fork as we need that fix right now ;-)

**Comment by 4-20ma** [comment]
I've experienced the same error on an older machine with `platform_version: 10.9.5`. My machines with `platform_version: 10.11.6` work fine. I'm looking forward to the PR being accepted.

omnibus_updater@2.0.0
```
Relevant File Content:
----------------------
/var/chef/cache/cookbooks/omnibus_updater/recipes/downloader.rb:

 26:    version = node['omnibus_updater']['version'] || ''
 27:    remote_path = OmnibusTrucker.url(
 28:      OmnibusTrucker.build_url(node,
 29:        version: node['omnibus_updater']['force_latest'] ? nil : version.sub(/\-.+$/, ''),
 30:        prerelease: node['omnibus_updater']['preview']
 31:                              ), node
 32:    )
 33>>   raise 'Did not find path' if remote_path.nil?
 34:  end
 35:  
 36:  if remote_path
 37:    node.normal['omnibus_updater']['full_url'] = remote_path
 38:  
 39:    directory node['omnibus_updater']['cache_dir'] do
 40:      recursive true
 41:    end
 42:  
```

**Comment by 4-20ma** [comment]
If I understand the _intent_ of the version comparison, it's to return the higher of a) current platform_version or b) 10.7. If this is the case, the proposed PR #127 still contains an error.

Test via `irb`:
```ruby
# correct -- expect "10.7"
irb(main):050:0> ["10.7","10.7"].max { |x,y| x.to_f <=> y.to_f }
=> "10.7"

# correct -- expect "10.8"
irb(main):051:0> ["10.8","10.7"].max { |x,y| x.to_f <=> y.to_f }
=> "10.8"

# correct -- expect "10.9"
irb(main):052:0> ["10.9","10.7"].max { |x,y| x.to_f <=> y.to_f }
=> "10.9"

# incorrect -- expect "10.10"
irb(main):053:0> ["10.10","10.7"].max { |x,y| x.to_f <=> y.to_f }
=> "10.7"

# incorrect -- expect "10.11"
irb(main):054:0> ["10.11","10.7"].max { |x,y| x.to_f <=> y.to_f }
=> "10.7"

# correct -- expect "10.7"
irb(main):055:0> ["10.6","10.7"].max { |x,y| x.to_f <=> y.to_f }
=> "10.7"

# correct -- expect "10.7"
irb(main):056:0> ["10.5","10.7"].max { |x,y| x.to_f <=> y.to_f }
=> "10.7"
```


We want something like the following:

```ruby
[[major, minor], [10, 7]].max { |x,y| x <=> y }.join('.')
```
or
```ruby
[[major, minor], '10.7'.split('.')].max { |x,y| x <=> y }.join('.')
```


Test via `irb:
```ruby
# correct -- expect "10.7"
irb(main):042:0> [[10,7],[10,7]].max { |x,y| x <=> y }.join('.')
=> "10.7"

# correct -- expect "10.8"
irb(main):043:0> [[10,8],[10,7]].max { |x,y| x <=> y }.join('.')
=> "10.8"

# correct -- expect "10.9"
irb(main):044:0> [[10,9],[10,7]].max { |x,y| x <=> y }.join('.')
=> "10.9"

# correct -- expect "10.10"
irb(main):045:0> [[10,10],[10,7]].max { |x,y| x <=> y }.join('.')
=> "10.10"

# correct -- expect "10.11"
irb(main):046:0> [[10,11],[10,7]].max { |x,y| x <=> y }.join('.')
=> "10.11"

# correct -- expect "10.7"
irb(main):047:0> [[10,6],[10,7]].max { |x,y| x <=> y }.join('.')
=> "10.7"

# correct -- expect "10.7"
irb(main):048:0> [[10,5],[10,7]].max { |x,y| x <=> y }.join('.')
=> "10.7"

# correct -- expect "10.7"
irb(main):049:0> [[10,4],[10,7]].max { |x,y| x <=> y }.join('.')
=> "10.7"
```

**Comment by 4-20ma** [comment]
PR #127 was updated with commit eadb3e043a6179c443d41c9db191d7d0f4f00f60, delivering the expected behavior:

```ruby
[[major, minor].join('.'), '10.7'].max { |x,y| Gem::Version.new(x) <=> Gem::Version.new(y)}}
```

@Elias-from-Testfabrik all it needs from you are some spaces between commas to fix the style errors and a signed CLA.

**Comment by tas50** [comment]
We've merged the fix for this issue to master
