### ISSUE TITLE
Updating stopped working

### ISSUE THREAD

**Issue by Gary-Armstrong** [chef-cookbooks/omnibus_updater#128]
I want to first say that I'm rather new to this and my troubleshooting is almost certainly lacking.  Please let me know how to improve myself.

I've been using chef-client 12.9.38 for a while now and recently I changed my version in my environment like so:
```
  "override_attributes": {
    "omnibus_updater": {
      "version": "12.13.37",
      "prevent_downgrade": "true"
    },
```
This did cause omnibus_updater to update one of my instances but not another.  I was advised to see if my overrides were not working and so used chef-shell -z to get:
```
Ohai2u!
chef (12.9.38)> node['omnibus_updater']['version']
 => "12.13.37"
```

At the moment I'm stuck.  Google isn't being helpful.  So, I must turn to github issues.  Apologies if this is a user issue and not a cookbook issue.

**Comment by nmattam** [comment]
Maybe I ran into this today trying to upgrade 12.4.3 to 12.5.1. installer recipe is skipping every action with action nothing.
```
Recipe: omnibus_updater::downloader
  * directory[/var/chef/cache/omnibus_updater] action create (up to date)
  * remote_file[omnibus_remote[chef-12.5.1-1.el6.x86_64.rpm]] action create_if_missing
    - create new file /var/chef/cache/omnibus_updater/chef-12.5.1-1.el6.x86_64.rpm
    - update content in file /var/chef/cache/omnibus_updater/chef-12.5.1-1.el6.x86_64.rpm from none to 76dda2
    (file sizes exceed 10000000 bytes, diff output suppressed)
Recipe: omnibus_updater::old_package_cleaner
  * file[/var/chef/cache/omnibus_updater/chef-12.4.3-1.el6.x86_64.rpm] action delete
    - delete file /var/chef/cache/omnibus_updater/chef-12.4.3-1.el6.x86_64.rpm
Recipe: omnibus_updater::installer
  * service[chef-client-omnibus] action nothing (skipped due to action :nothing)
  * file[/tmp/nocheck] action create (skipped due to only_if)
  * ruby_block[omnibus chef killer] action nothing (skipped due to action :nothing)
  * execute[omnibus_install[chef-12.5.1-1.el6.x86_64.rpm]] action nothing (skipped due to action :nothing)
  * ruby_block[Omnibus Chef install notifier] action nothing (skipped due to action :nothing)
```
Maybe the [subscribe](https://github.com/chef-cookbooks/omnibus_updater/blob/master/recipes/installer.rb#L107) resource is not doing the job.

**Comment by bradfeehan** [comment]
Think I've been affected by this as well.

**Comment by eherot** [comment]
Interestingly, setting `node['omnibus_updater']['always_download'] = true` seems to work around this issue...

**Comment by nmattam** [comment]
I got past this issue by locking compact_resource to 12.9.0. I was aware that there was an [issue](https://github.com/chef-cookbooks/compat_resource/issues/87) with notifications (even though that was not what I was seeing here) when compact_resource is used. I had a cookbook in my run_list that was pulling in compact_resource and that might have messed with the subscribe resource.

**Comment by eherot** [comment]
Interesting workaround. Kind of problematic since current versions of `build-essential` and `ohai` both depend on `compat_resource >= 12.10`, tho...

**Comment by nmattam** [comment]
Came across https://github.com/chef-cookbooks/compat_resource/issues/99 today.

**Comment by lamont-granquist** [comment]
almost certain this is the subscribes bug in compat_resource which is now fixed.
