### ISSUE TITLE
Dir.glob() doesn't support backslash

### ISSUE THREAD

**Issue by rlaveycal** [chef-cookbooks/omnibus_updater#129]
In the old_package_cleaner.rb recipe Dir.glob() is used to find previous installers. On Windows `node['omnibus_updater']['cache_dir']` will resolve to a path with `\` resulting in no matches. It needs a `.gsub('\\','/')` appended to it.

**Comment by tas50** [comment]
This issue has been solved in the new chef_client_updater cookbook. I'm going to close this issue out here since we've deprecated this cookbook in favor of the new method. We believe it provides a much better experience and encourage everyone to try it out.
