### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by tadukurow** [chef-cookbooks/omnibus_updater#131]
I would like to know if FreeBSD is supported. 
Both freebsd-9.3 and freebsd-10.3 are in the kitchen test file.
However the default recipe explicitly doesn't support freebsd.

Tests with freebsd are passing so why is it not on the supported platforms list?

**Comment by tas50** [comment]
This issue has been solved in the new chef_client_updater cookbook. I'm going to close this issue out here since we've deprecated this cookbook in favor of the new method. We believe it provides a much better experience and encourage everyone to try it out.
