### ISSUE TITLE
Solaris .p5p package not supported

### ISSUE THREAD

**Issue by ezray** [chef-cookbooks/omnibus_updater#132]
The Solaris 11 Chef client is now distributed as a .p5p package file. Omnibus_updater doesn't know how to deal with this package type, so the Chef run fails with an `Unknown package type encountered for install: .p5p` error.

**Comment by tas50** [comment]
This issue has been solved in the new chef_client_updater cookbook. I'm going to close this issue out here since we've deprecated this cookbook in favor of the new method. We believe it provides a much better experience and encourage everyone to try it out.
