### ISSUE TITLE
MSI install dir

### ISSUE THREAD

**Issue by lbn-chef-team** [chef-cookbooks/omnibus_updater#136]
Can you add the the installation directory available for msiexec property. Actually when not using the default path, the upgrade change the location of binary. The MSI of chef-client is already using a param named INSTALLLOCATION.. So this could be fixed using the following code:

 at line 41 on installer.rb:  
`command "msiexec.exe /qn /i #{File.basename(remote_path)} ADDLOCAL=\"#{node['omnibus_updater']['addlocal']}\" INSTALLLOCATION=\"#{node['omnibus_updater']['installpath']}\"" `

instead of:
`command "msiexec.exe /qn /i #{File.basename(remote_path)} ADDLOCAL=\"#{node['omnibus_updater']['addlocal']}\""`

with add a default value (in attributes/default.rb):
`node['omnibus_updater']['installpath'] = 'c:\opscode'`

Best Regards,

**Comment by modille** [comment]
You can create a wrapper cookbook to get around this for now, if you want.

https://sethvargo.com/changing-chef-resources-at-runtime/
https://coderanger.net/rewind/
https://docs.chef.io/release/devkit/dsl_recipe.html#id3

Something like this would work if you wrapped around [v2.0.0](https://github.com/chef-cookbooks/omnibus_updater/blob/v2.0.0/recipes/installer.rb):

```ruby
# metadata.rb
depends 'omnibus_updater', '= 2.0.0'

# recipes/default.rb
include_recipe 'omnibus_updater::default'

if platform?('windows')
  if node['chef_packages']['chef']['version'] != node['omnibus_updater']['version']
    config_location  = 'x:/chef'
    install_location = 'x:/opscode'

    edit_resource!(:execute, 'chef-install') do
      command "msiexec.exe /qn /i #{File.basename(node['omnibus_updater']['full_url'])}" \
              " ADDLOCAL=\"#{node['omnibus_updater']['addlocal']}\"" \
              " CONFIGLOCATION=\"#{config_location}\"" \
              " INSTALLLOCATION=\"#{install_location}\""
    end
  end
end
```

Up to you how you would determine the values for `config_location` and `install_location`.

**Comment by lbn-aaio-team** [comment]
Great solution, I did not know the "edit_resource!". Seems to be handy.
Thanks for your help.

Regards,

**Comment by tas50** [comment]
At this time we've chosen to deprecate the omnibus_updater cookbook in favor of our new chef_client_updater cookbook. I'm going to close this issue out as we will not be updating or releasing new versions of this codebase. Check out the new code at https://github.com/chef-cookbooks/chef_client_updater
