### ISSUE TITLE
Prevent downgrade on Windows

### ISSUE THREAD

**Issue by modille** [chef-cookbooks/omnibus_updater#137]
The `prevent_downgrade` attribute doesn't prevent the install resources from executing on Windoze platforms like it does on non-Windoze platforms.

It will prevent the download from happening, but the install resources will still execute and end up failing due to the msi not existing.

Is there a good reason that the notification and guard logic isn't more similar between the two?

https://github.com/chef-cookbooks/omnibus_updater/blob/7848b97d8d01bc956d4840080e1dee83d993c50f/recipes/installer.rb#L104

```ruby
ruby_block 'Omnibus Chef install notifier' do
  ...
  subscribes :create, "remote_file[omnibus_remote[#{File.basename(remote_path)}]]", :immediately
  only_if { node['chef_packages']['chef']['version'] != node['omnibus_updater']['version'] }
end
```

https://github.com/chef-cookbooks/omnibus_updater/blob/7848b97d8d01bc956d4840080e1dee83d993c50f/recipes/installer.rb#L50

```ruby
ruby_block 'Omnibus Chef Update' do
  ...
  not_if { chef_version == "Chef: #{version}\r\n" }
end
```

**Comment by tas50** [comment]
This issue has been solved in the new chef_client_updater cookbook. I'm going to close this issue out here since we've deprecated this cookbook in favor of the new method. We believe it provides a much better experience and encourage everyone to try it out.
