### ISSUE TITLE
Omnibus_updater causes rpmdb corruption on EL6 and EL7

### ISSUE THREAD

**Issue by erenfro** [chef-cookbooks/omnibus_updater#141]
I have recently discovered that Omnibus updater is the root cause of my rpmdb becoming constantly corrupted. After running chef-client on schedule, including regular uses of omnibus_updater in the run_list, I had noticed my chef-client runs would start to fail, and did so within a day to at most a week. 

I run 3 physical servers and anywhere from 12 to 20 virtual machines on them in a Proxmox VE cluster, backed by Ceph running storage within the same physical machines running the hypervisors. Sometimes the disk I/O can become a little starved, especially while ceph is doing a deep scrubbing. 

My instances running both CentOS 6.8 and CentOS 7.2-7.3 would both exhibit rpmdb corruptions causing the chef-client runs to start failing. As soon as I removed the omnibus_updater from my run list, I noticed this problem immediately stopped and I haven't seen it since.

I'm guessing that part of the problem is how this cookbook is directly utilizing rpm commands instead of using yum or other similar methods. The way I usually install the chef-client for my test-kitchen images is with packer using
yum https://packages.chef.io/files/stable/chef/$ver/el/$rel/chef-$ver-$build.el$rel.$arch.rpm

This is because yum itself can directly install and follow with any dependencies it needs from a remote URL directly. I'm not sure about what zypper could do, but perhaps you should consider this option with this cookbook for at least rhel family, don't even need the downloader cookbook.

**Comment by cheeseplus** [comment]
Is there a reliable repro for this case?

**Comment by tas50** [comment]
This issue has been solved in the new chef_client_updater cookbook. I'm going to close this issue out here since we've deprecated this cookbook in favor of the new method. We believe it provides a much better experience and encourage everyone to try it out.
