### ISSUE TITLE
Not an Issue but need some inputs.

### ISSUE THREAD

**Issue by sarfraz17** [chef-cookbooks/omnibus_updater#142]
The article talks about the nodes which have internet connectivity, but in a situation if their is no internet connectivity then how can we fetch the package and upgrade the client. The option we are looking at is to use nexus as artefact management.

Any thoughts.

**Comment by sarfraz17** [comment]
Any suggestions please

**Comment by cheeseplus** [comment]
@sarfraz17 in that case manage the packages how you see fit, there isn't a right answer but if you want to use this cookbook internet connectivity is expected.

The easiest route would be put the package in a repository such as Nexus and if that has apt/yum support simply write your own cookbook to install and upgrade the package. 

Closing this issue as it's hard to provide an authoritative list of ways to do this but I encourage you to join us in http://community-slack.chef.io/ where you can get more realtime help.
