### ISSUE TITLE
Support Windows msi files

### ISSUE THREAD

**Issue by jeppenejsum** [chef-cookbooks/omnibus_updater#32]
Currently, when running on windows, you get an error:

Unknown package type encountered for install

**Comment by spuder** [comment]
+1

**Comment by slyness** [comment]
This may well be resolved very soon.. woo!

**Comment by Stromweld** [comment]
@slyness are you guys planning a release to master soon so the windows bits can get into the supermarket and then this issue should be able to be closed.

**Comment by tas50** [comment]
Closing this since the current release includes this support
