### ISSUE TITLE
The ruby implementation of install.sh should be removed

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/omnibus_updater#46]
This cookbook should use install.sh directly rather than reimplementing it in ruby.  The current situation requires porting all the omnitruck features to ruby and will always lag and introduce more bug incompatibilities.

Feature requests should be opened against omnitruck in order to support kill-if-upgraded and never-downgrade, which look to me like they're currently the reasons why using install.sh directly is difficult.

**Comment by ncerny** [comment]
+1

Do we have any updates?  Can https://github.com/hw-cookbooks/omnibus_updater/commit/9afba4250fac0dee9724261093cd1bc6e0448932 be merged in?

**Comment by nwatnickchef** [comment]
+1 update?

**Comment by bdangit** [comment]
:+1:

**Comment by sclark007** [comment]
:+1: is this cookbook being supported anymore? we have lots of systems that need the chef client updated due to CVE based updates. is there another solution?

**Comment by lamont-granquist** [comment]
Internally Chef is working on mixlib-install:
  
https://github.com/chef/mixlib-install

That will provide a unified ruby library for wrapping installing from omnibus installers.  We plan on getting that into test-kitchen, vagrant-omnibus, hopefully this cookbook and other places where have different code which is all trying to do basically the same thing and hit omnitruck and pull down artifacts.

We're also discussing baking this cookbooks functionality directly into core chef itself.

However note that thom is on version 0.3.0 of mixlib-install and that his initial commit was "a day ago" according to github.   So we're going to be actively working on solving this problem, but taking a bit larger approach than just bugfixing this cookbook.

**Comment by lamont-granquist** [comment]
Oh it may simplify everyone's life to use the packagecloud.io repos directly:

https://packagecloud.io/chef/stable/install

If you click on the 'chef' tab you can see how to use the "packagecloud" cookbook to install the stable repo for debs or rpms:

https://github.com/computology/packagecloud-cookbook

Then you can just use the Chef package resource itself to update Chef.  You'll probably want to hang a notification off of the package resource that triggers a ruby_block which aborts the current chef-client run (or dig into this cookbook to figure out how that works here) because continuing the current chef-client run after you've swapped out the packages underneath it is going to fail reasonably often (nothing to be done about that).

**Comment by lamont-granquist** [comment]
```
packagecloud_repo "chef/stable" do
  type "deb" # or "rpm"
end
 
package "chef" do
  version node['myorg']['chef-client-version']
  action :install
  notifies :run, 'ruby_block[omnibus chef killer]', :immediately
end
 
# Continuing with a chef client run after the client has been upgraded will give undetermined results
ruby_block 'omnibus chef killer' do
  block do
    raise 'New omnibus chef version installed. Killing Chef run!'
  end
  action :nothing
end
```

**Comment by ncerny** [comment]
@lamont-granquist - that solution doesn't work for OSX which is a major concern right now.

**Comment by lamont-granquist** [comment]
We're looking at fixing that internally with the mixlib-install work and other stuff, but those are efforts that are just kicking off, they won't help you immediately.

**Comment by icberg7** [comment]
Another thing of note is that, to my knowledge, the packageloud-cookbook does not support proxy configuration of any kind, so if the `install.sh` is the preferred method, we should make sure that folks behind a firewall still have a way of upgrading.

**Comment by chewi** [comment]
The packagecloud cookbook has always worked for me from behind a proxy. It just uses the system's package manager so why wouldn't it work?

**Comment by icberg7** [comment]
I believe it would work if you have a global proxy setting, but it doesn't support configuring a proxy for a single repository. My organization has internal mirrors for all the core operating system repositories, so I only need to set a proxy for packagecloud.

**Comment by tas50** [comment]
https://github.com/chef-cookbooks/chef-client/pull/452 is the WIP PR to solve this based off the work that @wjordan did

**Comment by tas50** [comment]
This issue has been solved in the new chef_client_updater cookbook. I'm going to close this issue out here since we've deprecated this cookbook in favor of the new method. We believe it provides a much better experience and encourage everyone to try it out.
