### ISSUE TITLE
Need code for installation of DMGs on mac

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/omnibus_updater#47]
Next version of chef will ship with DMGs for mac, so the installation method needs to be updated to mount the dmg and install it.

**Comment by aktec** [comment]
add this lines to recipes/installer.rb
```
      when '.dmg'
        command "hdiutil attach #{File.join(node[:omnibus_updater][:cache_dir], File.basename(remote_path))} && installer -package \"/Volumes/Chef Client/#{File.basename(remote_path, ".*")}.pkg\" -target /"
```
after line 86 (solaris).

It fix issue for me.

**Comment by tas50** [comment]
We have DMG support now https://github.com/chef-cookbooks/omnibus_updater/blob/master/recipes/installer.rb#L86
