### ISSUE TITLE
SSL validation of HTTPS requests

### ISSUE THREAD

**Issue by rastasheep** [chef-cookbooks/omnibus_updater#51]
After updating to Chef 11.12.2 there is warning:

```
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
SSL validation of HTTPS requests is disabled. HTTPS connections are still
encrypted, but chef is not able to detect forged replies or man in the middle
attacks.

To fix this issue add an entry like this to your configuration file:

```
  # Verify all HTTPS connections (recommended)
  ssl_verify_mode :verify_peer

  # OR, Verify only connections to chef-server
  verify_api_cert true
```

To check your SSL configuration, or troubleshoot errors, you can use the
`knife ssl check` command like so:

```
  knife ssl check -c /etc/chef/client.rb
```

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
```

What is the best way to fix this, any suggestions?

**Comment by tas50** [comment]
You need to update your Chef client.rb to enable this. In Chef 12 it's on by default.  Check docs.chef.io for client.rb suggestions
