### ISSUE TITLE
Optionally keep downloaded cache

### ISSUE THREAD

**Issue by webframp** [chef-cookbooks/omnibus_updater#58]
As mentioned here: http://lists.opscode.com/sympa/arc/chef/2014-08/msg00215.html

It might not be a bad idea to support this perhaps just via a new attribute defaulted to false?

`default[:omnibus_updater][:cache_preserve] = false`

**Comment by tas50** [comment]
default['omnibus_updater']['cache_omnibus_installer'] is an option now
