### ISSUE TITLE
No support for CentOS 7

### ISSUE THREAD

**Issue by marcoamorales** [chef-cookbooks/omnibus_updater#61]
omnibus_updater will fail to pull the right package for CentOS 7.

**Comment by joerocklin** [comment]
It seems like getting #46 fixed and merged would help a lot of things. CentOS has released 7.1 and adoption is increasing. I would love to help get this moving along as we're hitting issues, but I can't tell what direction the repo owners want to go. Would it be possible to get some update as to when this might be resolved or how best to help get a resolution moved through?

**Comment by tmaier** [comment]
+1

**Comment by MattMencel** [comment]
:+1:

**Comment by sspans** [comment]
This does seem to work just fine with newer versions...

**Comment by tas50** [comment]
This is fixed in the latest releases.
