### ISSUE TITLE
If Chef is downgraded for any reason, cache prevents install from running

### ISSUE THREAD

**Issue by joshk0** [chef-cookbooks/omnibus_updater#65]
Ran into this while working on #64. Assume Chef version A < B.
1. install version A of Chef on a test machine.
2. Use omnibus_updater attributes to upgrade Chef to version B.
3. Manually reinstall version A.
4. Rerun chef. Version B is not installed because the install notifier does not run.

The (quite complicated) logic in the downloader should still trigger the install notifier if Chef is a different version, even if the remote_file is already in the cache.

**Comment by lamont-granquist** [comment]
looks like a dup of #54 and should probably be closed.

**Comment by tas50** [comment]
This issue has been solved in the new chef_client_updater cookbook. I'm going to close this issue out here since we've deprecated this cookbook in favor of the new method. We believe it provides a much better experience and encourage everyone to try it out.
