### ISSUE TITLE
Cannot build with chef-solo behind a proxy

### ISSUE THREAD

**Issue by munjeli** [chef-cookbooks/omnibus_updater#80]
Where can I set a proxy var that will work with this cookbook? I'm using packer with the chef-solo provisioner and omnibus_updater is hanging when I try to build behind a proxy. I have set env vars all over the place and in the execute command for the chef run, but it always hangs.

**Comment by tas50** [comment]
At this time we've chosen to deprecate the omnibus_updater cookbook in favor of our new chef_client_updater cookbook. I'm going to close this issue out as we will not be updating or releasing new versions of this codebase. Check out the new code at https://github.com/chef-cookbooks/chef_client_updater
