### ISSUE TITLE
Cryptic error message when omnitrucker url() fails

### ISSUE THREAD

**Issue by erkolson** [chef-cookbooks/omnibus_updater#87]
If omnitrucker url fails in this step:
https://github.com/hw-cookbooks/omnibus_updater/blob/develop/libraries/omnitrucker.rb#L84

This remote_path url is never set:
https://github.com/hw-cookbooks/omnibus_updater/blob/develop/recipes/downloader.rb#L27

And the remote_file[omnibus_remote[...]] resource is never instantiated.
https://github.com/hw-cookbooks/omnibus_updater/blob/develop/recipes/downloader.rb#L42-L66

You get an error like this:

```
  Chef::Exceptions::ResourceNotFound
  ----------------------------------
  Cannot find a resource matching remote_file[omnibus_remote[chef_12.4.3-1_amd64.deb]] (did you define it first?)

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/omnibus_updater/recipes/installer.rb:65:in `block in from_file'
    /var/chef/cache/cookbooks/omnibus_updater/recipes/installer.rb:62:in `from_file'
    /var/chef/cache/cookbooks/omnibus_updater/recipes/default.rb:26:in `from_file'
    /var/chef/cache/cookbooks/platform-base/recipes/default.rb:142:in `from_file'
```

If someone were to run the omnibus_updater as part of a 'base' role in their various environments, something like this issue - http://status.chef.io/post/135204038311/issue-with-the-omnitruck-download-server , would trigger this bug and cause every chef run on every node to fail.

**Comment by iroller** [comment]
Noticed this error multiple times today

**Comment by tas50** [comment]
This issue has been solved in the new chef_client_updater cookbook. I'm going to close this issue out here since we've deprecated this cookbook in favor of the new method. We believe it provides a much better experience and encourage everyone to try it out.
